# Generated by Django 4.2.1 on 2023-07-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_ffowers_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='owner_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
