# Generated by Django 4.2.1 on 2023-07-12 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_posts_liked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='post_id',
        ),
    ]
